# Generated by Django 5.2.11 on 2026-02-07 12:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=100, verbose_name='Altyazı1')),
                ('caption2', models.CharField(max_length=100, verbose_name='Altyazı2')),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Ölçü: 1920x570', upload_to='')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('name', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hizmet Adı')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Hizmet Açıklaması')),
                ('image', models.ImageField(upload_to='', verbose_name='Hizmete Özgü Bir Resim Koy')),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(verbose_name='Hizmet Aktif Mi')),
            ],
        ),
    ]
