# Generated by Django 5.0 on 2026-02-08 11:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_big',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Geniş Açıklama ve Yazı'),
            preserve_default=False,
        ),
    ]
