# Generated by Django 5.2.11 on 2026-02-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service_description_big'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Hizmet Açıklaması'),
        ),
    ]
