# Generated by Django 5.2.11 on 2026-02-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_service_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
