# Generated by Django 5.2.11 on 2026-02-08 12:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hizmet Adı')),
                ('description', models.TextField(verbose_name='Hizmet Açıklaması')),
                ('description_big', ckeditor.fields.RichTextField(verbose_name='Geniş Açıklama ve Yazı')),
                ('image', models.ImageField(upload_to='', verbose_name='Hizmete Özgü Bir Resim Koy')),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(verbose_name='Hizmet Aktif Mi')),
            ],
        ),
    ]
