# Generated by Django 5.2.11 on 2026-02-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceModel',
        ),
    ]
